<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1748356893271' stop='1748356968530'>
    <name>[SMOKE] Get server groups endpoint</name>
    <title>[SMOKE] Get server groups endpoint</title>
    <test-cases>
        <test-case start='1748356893271' status='failed' stop='1748356908333'>
            <name>should respond with valid status code and data structure</name>
            <title>should respond with valid status code and data structure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups. Method: get</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroups.spec.js:15:26)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356908335' status='failed' stop='1748356923386'>
            <name>put method should respond with status code 405 and an error message</name>
            <title>put method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups. Method: put</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroups.spec.js:62:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356923388' status='failed' stop='1748356938438'>
            <name>post method should respond with status code 405 and an error message</name>
            <title>post method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups. Method: post</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroups.spec.js:62:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356938444' status='failed' stop='1748356953482'>
            <name>patch method should respond with status code 405 and an error message</name>
            <title>patch method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups. Method: patch</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroups.spec.js:62:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356953483' status='failed' stop='1748356968528'>
            <name>del method should respond with status code 405 and an error message</name>
            <title>del method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups. Method: delete</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroups.spec.js:62:28)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>