<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1748356817884' stop='1748356893262'>
    <name>[SMOKE] Get server group types endpoint</name>
    <title>[SMOKE] Get server group types endpoint</title>
    <test-cases>
        <test-case start='1748356817885' status='failed' stop='1748356833038'>
            <name>should respond with valid status code and data structure</name>
            <title>should respond with valid status code and data structure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups/types. Method: get</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroupTypes.spec.js:16:26)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356833045' status='failed' stop='1748356848096'>
            <name>put method should respond with status code 405 and an error message</name>
            <title>put method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups/types. Method: put</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroupTypes.spec.js:54:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356848098' status='failed' stop='1748356863160'>
            <name>post method should respond with status code 405 and an error message</name>
            <title>post method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups/types. Method: post</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroupTypes.spec.js:54:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356863165' status='failed' stop='1748356878207'>
            <name>patch method should respond with status code 405 and an error message</name>
            <title>patch method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups/types. Method: patch</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroupTypes.spec.js:54:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356878209' status='failed' stop='1748356893260'>
            <name>del method should respond with status code 405 and an error message</name>
            <title>del method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/groups/types. Method: delete</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverGroupTypes.spec.js:54:28)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>