<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1748356742513' stop='1748356817876'>
    <name>[SMOKE] Get server countries endpoint</name>
    <title>[SMOKE] Get server countries endpoint</title>
    <test-cases>
        <test-case start='1748356742513' status='failed' stop='1748356757582'>
            <name>should respond with valid status code and data structure</name>
            <title>should respond with valid status code and data structure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/countries. Method: get</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverCountries.spec.js:19:26)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356757584' status='failed' stop='1748356772666'>
            <name>put method should respond with status code 405 and an error message</name>
            <title>put method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/countries. Method: put</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverCountries.spec.js:60:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356772669' status='failed' stop='1748356787727'>
            <name>post method should respond with status code 405 and an error message</name>
            <title>post method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/countries. Method: post</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverCountries.spec.js:60:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356787728' status='failed' stop='1748356802805'>
            <name>patch method should respond with status code 405 and an error message</name>
            <title>patch method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/countries. Method: patch</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverCountries.spec.js:60:28)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1748356802808' status='failed' stop='1748356817874'>
            <name>del method should respond with status code 405 and an error message</name>
            <title>del method should respond with status code 405 and an error message</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Endpoint is not responding. 5 attempts has been made with 3 seconds apart. Endpoint: https://127.0.0.1/v1/servers/countries. Method: delete</message>
                <stack-trace>    at next (/app/node_modules/@nordvpn/tests-backend-core/src/request.js:38:11)
                    at /app/node_modules/@nordvpn/tests-backend-core/src/request.js:34:16
                    at async UserContext.&lt;anonymous> (/app/tests/smoke/serverCountries.spec.js:60:28)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>